MicroEJ/docs

_themes/microej/static/css/microej.css, conf.py
* Removes GitHub links from the flyout
* Doesn't "collapse" navigation links. This makes all of the navigation
heading expandable, and also gives the user the ability to browse the
navigation without navigating to a new page (by selecting the `[+]`
icon)
=> Remove GitHub links and use uncollapsed navigation

PlatformDeveloperGuide/mock.rst
`suspendCurrentJavaThread`/`SNI_getCurrentJavaThreadID`/`SNI_resumeJavaThread`
are not implemented. Use `notifyAll` and `wait` methods on a lock
monitor in a mock to implement this behavior.
=> M0127CC-572 Document `notifyAll`/`wait` mechanics

overview/systemRequirements.rst
Changes :
* Windows 7, Windows Vista and Windows XP SP3 removed since these editions reached their end of life
* Ubuntu versions set to the latest LTSs
* MacOS 10.10 Yosemite and 10.11 El Capitan removed since these editions reached their end of life
* MacOS 10.13 added since it is used by some MicroEJ employees
* Java requirements added
=> M0137W-469 Update SDK requirements

ApplicationDeveloperGuide/mmm.rst
Point to root repository, github will render the README.rst properly (correct URL to README.rst is blob/...).
=> Fix incorrect link to CLI in mmm.rst

PlatformDeveloperGuide/platformOverview.rst
- Remove redundant "Step X".  The list is already numbered, no need to
repeat the step number.
- Rephrase to fit with the new wording (without "Step X")
- Mention MicroEJ Firmware instead of "binary application" as per the
glossary.
=> Improve platform overview

PlatformDeveloperGuide/platformCreation.rst
The tool is called `Platform Editor` in the SDK, not `Platform description editor`.
=> Fix Platform Editor naming

ApplicationDeveloperGuide/mmm.rst, Tutorials/tutorialSetupBuildUsingJenkinsAndArtifactory.rst
- Bump to MMM spec 2.0-E
- Add Module Dependency section
- Explain how to set the MMM matching rule on a dependency
- Document dependency visiblity in MMM
- Document ivy-update easyant plugin
- Explain how to enable MMM semantic for a module
- Document Build Options target property in mmm.rst
- Fix title level
- Explain how to customize the target folder when building with Jenkins
Thanks @tdelhomenie & @friviere for the review.
Preview: https://docs.microej.com/en/feature-m0078ddg-355_improve_mmm_doc
=> Improve MMM documentation

ApplicationDeveloperGuide/mmm.rst
This PR updates the download link of the CLI to the release 0.1.0.
It also removes the quotes in TOML configuration file because of the bug https://youtrack.cross/issue/M0090IDE-3517.
=> M0228J-91 Update download link of the CLI to the release 0.1.0

PlatformDeveloperGuide/platformCreation.rst
- useless with architectures uploaded to repository.microej.com up to
7.14.0 (without ivy.xml) - was not used in Wrover Platform
https://github.com/MicroEJ/Platform-Espressif-ESP-WROVER-KIT-V4.1/blob/master/ESP32-WROVER-Xtensa-FreeRTOS-configuration/module.ivy#L31
- useless and fails download of architecture 7.15.0 with ivy.xml and new
naming convention (no default conf)
=> remove the default conf when fetching architecture

PlatformDeveloperGuide/platformCreation.rst
deploy.dir.microejscript is the absolute path to microejscript.
deploy.bsp.microejscript is a boolean flag.
=> Fix deploy.dir.microejscript option name

.readthedocs.yml, KernelDeveloperGuide/featuresCommunication.rst, Makefile, PlatformDeveloperGuide/ui.rst, conf.py
This PR changes the sphinx and readthedocs configuration to make the build fails if there are warnings. The change done in the Makefile allows to apply this change when building the doc locally. The change done in the file `.readthedocs.yml` allows to apply this change when building the doc on ReadTheDocs.
It also fixes the warnings to make the build pass. And I took this opportunity to update the copyright.
=> M0078DDG-368 Make warnings fail the build

ApplicationDeveloperGuide/js/builtin.rst
Exclude Number.toString from supported methods since most of the tests on it fail.
=> M0228J-148 Exclude Number.toString from supported methods

ApplicationDeveloperGuide/repository.rst
The ivy `repository` configuration is required as per the declaration
above, but this configuration is not (yet) created by default in the
skeleton.
=> Explain how to add the ivy `repository` configuration when embedding a module in a repository

PlatformDeveloperGuide/mock.rst
to allow correct low priority threads scheduling, a wait or a sleep must
be wrapped by notifySuspendStart() and notifySuspendEnd()
=> update mock section "Blocking Native Methods"

ApplicationDeveloperGuide/moduleNatures.rst
- Fix description and default value of microej.testsuite.properties.s3.cc.activated property
- Remove the property bar.javadoc.stylesheet.file for the Module Repostiory build type since it is not used
=> M0078DDG-377 Modules natures fixes

overview/licenses.rst
Fix double occurrence of the word `contact` in the licenses documentation.
=> Fix typo in licenses documentation

glossary.rst
MICROEJ is for marketing product terms
=> keep MicroEJ for technical terms (case sensitive)

Tutorials/getStartedWithGUI/index.rst
start with a verb like other tutorials
(https://github.com/MicroEJ/docs/pull/257#discussion_r671182038 : the
folder was correctly renamed)
=> fix the GUI tutorial title with a verb

ApplicationDeveloperGuide/moduleNatures.rst
This change removes the features Test Suite and Artifact Checker from the Standalone Application since the addition of this features has not been released yet.
This change must be rollbacked when the SDK 5.5.0 is released.
=> M0078DDG-434 Remove unreleased features for Standalone Application nature

PlatformDeveloperGuide/architectureChangelog.rst
This issue exists from the beginning of BON Constant introduction
(7.11.0), but may throw different errors depending on the upper
architecture version
=> document known issue with if constant at the end of try block

Tutorials/getStartedWithGUI/setup.rst, conf.py
This change enables the linkchecker and removes the failing link : https://www.java.com/en/download/manual.jsp
This link seems correct but for some reasons it does not pass the linkchecker.
Also the linkchecker timeout has been set to 20 seconds to avoid to be stuck too much time on a failing link.
=> M0137W-616 Enable linkchecker and remove failing link

PlatformDeveloperGuide/architectureChangelog.rst
found during an old architecture 6.x validation
=> add a missing changelog line

SDKUserGuide/sdkChangeLog.rst, glossary.rst
- indicate the previous name in glossary as it was widely used in the
past, especially in samples README and forum posts
- replace Resident application -> System application except in plugin
label (Firmware Linker)
=> fix usage of resident application

SDKUserGuide/install.rst
Installation download has been moved to a new page. the previous linked page (getting started) no longer contains the download and installation instructions.
=> Fix installation URL

SDKUserGuide/mmm.rst
I propose to add a little detail on how to edit cacerts: it is also possible to change cacerts by opening Keystore Explorer with admin rights.
=> Add an option to edit cacerts

VEEPortingGuide/platformCreation.rst
According to documentation "deploy.bsp.microejscript=true" requires Platform at least configured with Partial BSP Connection
Setting 'deploy.dir.microejscript' is sufficient and triggers the build script (just remove the option if you do not want to trigger the build script)
=> Fix options for "No BSP Connection using SDK"

ApplicationDeveloperGuide/runtime.rst
Though this is the default with latest skeleton, I still encounter issues from time to time by customers that creates projects with an old SDK (for example 4.1.5) or with an non-microej skeleton (for example `std-java`).
This can cause problem because the semantic is different between 1.7 and 1.8. See https://forum.microej.com/t/cannot-refer-to-the-non-final-local-variable-foo-defined-in-an-enclosing-scope/1221 for such instance.
=> Mention explicitely the Compliance level required for MicroEJ applications

ApplicationDeveloperGuide/runtime.rst, VEEPortingGuide/coreEngine.rst
- Add abstraction layer section to Core VEE Porting guide
- Move use section from Core VEE Porting guide  to Application Guide Runtime page
=> Add abstraction layer section to Core VEE Porting guide

SDKUserGuide/sdkChangeLog.rst
https://docs.microej.com/en/feature-replace_java_11_by_jdk_11_in_sdk_5.7.0_changelog/SDKUserGuide/sdkChangeLog.html#changelog-5-7-0
=> replace Java 11 by JDK 11 in SDK 5.7.0 changelog

SDKUserGuide/resolveDependenciesInWorkspace.rst
https://docs.microej.com/en/feature-add_architecture_8_note_in_front_panel_resolveinworkspace_section/SDKUserGuide/resolveDependenciesInWorkspace.html#resolve-front-panel-in-workspace
=> Front Panel's resolve in Worspace requires SDK 5.7.0 and Archi 8.0

VEEPortingGuide/architecture7Migration.rst, VEEPortingGuide/architectureChangelog.rst
See https://docs.microej.com/en/feature-m0081meja-1990_remove_ecom/VEEPortingGuide/architectureChangelog.html#mm-dd
=> M0081MEJA-1990 Update architecture changelog after removing ECOM.

SDK6UserGuide/troubleshooting.rst
https://docs.microej.com/en/feature-microej-sdk-6_java_process_issue/SDK6UserGuide/troubleshooting.html#forked-java-process-still-running-after-the-interruption-of-a-build
=> add troubleshooting about forked Java process

VEEPortingGuide/architectureChangelog.rst
primitive type (e.g. ``byte.class``).
=> Added a check for unsupported access to the Class instance of a

ApplicationDeveloperGuide/sandboxedAppDeploy.rst
In case the `Platform` selected is a VDE, the `Settings` is empty and there is no indication about what is wrong.
=> Indicate the sandbox app deployment must be done with a VEE Port not a VDE

SDK6UserGuide/selectVeePort.rst
Saying "import a VEE Port" there caused me confusion because I was used to importing VEE Ports in my SDK (in SDK5).
But that is not the workflow in SDK6.
Remove the word "import" because the VEE Ports are not imported, we merely point at them.
=>  Reformulate a bit as VEE Ports are imported in SDK6

SDKUserGuide/sdkChangeLog.rst
I didn't fill the build types for SDK 5.0.1 because the tag Easyant4Eclipse v2.1.1 is missing.
=> Added a global list of build types per SDK version and added the list of latest buildtypes added per each SDK changelog entry

VEEPortingGuide/uiCco.rst, VEEPortingGuide/vgImage.rst
Upgrade to artifactory 7 seems to require the trailing '/' for correct redirection
=> fix links to forge.microej.commit

SDK6UserGuide/howtos/gradleSystemProperty.rst
https://docs.microej.com/en/feature-microej-sdk-6-update-howto-guide/SDK6UserGuide/howtos/gradleSystemProperty.html
=> remove the veePortPaths property from the gradleSystemProperty page

SDK6UserGuide/gettingStartedIMXRT595.rst
The MicroEJ support address can not be exposed publicly.
=> remove support mail address

SDK6UserGuide/runOnSimulator.rst
Fix code coverage option command line (add quotes) to make it run on Windows
=> Fix code coverage option command line

SDKUserGuide/mmm.rst
It seems any option added BEFORE the command is simply ignored.
=> MMM CLI: Options must be added AFTER the command

SDK6UserGuide/testProject.rst
Addition of a second missing **SystemProperties** in S3 coverage setup, essential for code coverage report generation.
=> Additional SystemProperties for s3 coverage w/ SDK6

VEEPortingGuide/coreEngine.rst
Even though it's explained above, when I looked at how to restart the core engine, I only looked at the `restart core engine` section, not the whole page.
=> Retell that createVM and destroyVM should be called only once

ApplicationDeveloperGuide/debuggerProxy.rst, SDK6UserGuide/licenses.rst, SDKUserGuide/licenses.rst
Update instructions to configure USB Dongle in WSL. 
According to https://learn.microsoft.com/en-us/windows/wsl/connect-usb#install-the-usbipd-win-project, commands have changed since usbipd-win 4.0.0
=> Update ubsipd wsl

ApplicationDeveloperGuide/classpath.rst
This PR documents how to use a resource that contains one of the Java Properties File specified delimiters in a MicroEJ app.
=> Add \ escape char when a resource name contains delimiter

KernelDeveloperGuide/kf.rst
The working "overlap" is confusing (especially when reading from top to bottom).
Indeed, the diagrams clarify the meaning of "overlap", but, IMO, the important sentence is "This is an upper bound, not a reservation".
I suggest some rewording to clarify that.
Also, from this documentation, I understand that the features cannot allocate more than what would leave the kernel less than its reserved memory. It is correct?
Another implementation could use the same mechanism than described in the feature criticality section  (with Kernel having some criticality level) but I don't think this is the case, right?
=> Clarify 'KF RAM Control: Managed Heap Configuration'

SDK6UserGuide/troubleshooting.rst
https://microej-docs--1369.com.readthedocs.build/en/1369/SDK6UserGuide/troubleshooting.html#fail-to-fetch-the-prod-version-of-an-architecture
=> Add a troubleshooting section on prod architecture fetch failure

ApplicationDeveloperGuide/sectionArchitectureOptions.rst, ApplicationDeveloperGuide/standaloneApplication.rst, Trainings/tutorialOptimizeMemoryFootprint.rst
We already fixed the application project template: https://github.com/MicroEJ/Tool-Project-Template-Application/pull/24
But I noticed the documentation also was stating the default value is `true`.
I checked and it seems it is not: see scripts/soar.xml
Maybe this was changed in some Architecture version but I found nothing in the changelog. @frivieremicroej ?
=> Fix default value for the application option 'soar.generate.classnames'
