DeviceDeveloperGuide/ui/display/display.rst, conf.py, microej.sty, rst_license_template.txt
updated license comment template for .rst files
testing tabularcolumns directive for tables with images
attempting to add a footer on PDF render
=> update 12/02/2020 : PDF tests and copyright

PlatformDeveloperGuide/sp.rst
- put filename and file extension in code quotes
- fix code indentation
- fix description of THERMOSTAT data in the example
=> Review sp section

PlatformDeveloperGuide/ssl.rst
The SSL page now mentions support of mutual authentication.
=> M0078DDG-294 Update SSL page

ApplicationDeveloperGuide/moduleNatures.rst, PlatformDeveloperGuide/mock.rst
- sort in alphabetical order
- fix bullet list
=> add mock link in summary table

ApplicationDeveloperGuide/mmm.rst
=> Revert "Feature/m0078 ddg 355 improve mmm doc"

ApplicationDeveloperGuide/microjs/getting_started.rst, ApplicationDeveloperGuide/mmm.rst, ApplicationDeveloperGuide/moduleNatures.rst
Add init CLI command and update MicroJS getting started page.
=> M0090IDE-3476 Add init CLI command and update MicroJS getting started page

ApplicationDeveloperGuide/UI/MicroUI/fonts.rst, ApplicationDeveloperGuide/UI/MicroUI/images.rst
- some errors were described as warnings
- an unknown input image format throws the same error than an unknown output format (no available image converter to read and encode the image)
=> Feature/m0078 ddg 370 UI tools

PlatformDeveloperGuide/platformCreation.rst, PlatformDeveloperGuide/platformOverview.rst
https://docs.microej.com/en/feature-m0018pqt-253_microej_pack_naming_convention
=> Document MicroEJ Packs flavors and packs naming convention

PlatformDeveloperGuide/index.rst, PlatformDeveloperGuide/platform.rst, PlatformDeveloperGuide/platformQualification.rst
https://docs.microej.com/en/feature-m0018pqt-288_core_ui_test_suite_versioning/PlatformDeveloperGuide/platformQualification.html
=> Add CORE and UI test suite versioning

PlatformDeveloperGuide/platformQualification.rst
=> tentative reduce again schematics

PlatformDeveloperGuide/platformQualification.rst
(just keep the pull up in toc)
=> rollback to previous title

PlatformDeveloperGuide/platformCreation.rst
this should be the final specification
=> augment run script specification with executable passed as parameter

ApplicationDeveloperGuide/js/builtin.rst, ApplicationDeveloperGuide/js/java.rst, ApplicationDeveloperGuide/js/limitations.rst
Remove limitations on arguments, built-in objects and update FFI generated code.
=> M0228J-43 Remove limitations on arguments, built-in objects and update FFI generated code

PlatformDeveloperGuide/appendix/tools/soar.rst
Add a link in the clinit cycle error description to the SOAR page to make easier to apply the suggested solution.
=> M0078DDG-415 Add a link in the clinit cycle error description to the SOAR page to make easier to apply the suggested solution

ApplicationDeveloperGuide/moduleNatures.rst
Add clarification about platform selection for source platforms
=> M0078DDG-422 Add clarification about platform selection for source platforms

ApplicationDeveloperGuide/UI/MWT/how-to-widget.rst
Provide guidelines about when to consume events and when not to consume events.
https://docs.microej.com/en/feature-m0137w-578_event_handling/ApplicationDeveloperGuide/UI/MWT/how-to-widget.html#consuming-events
=> Explain event consumption

Tutorials/tutorialSetupBuildUsingJenkinsAndArtifactory.rst
the package has slighlty changed (path to bin is `app/bin` instead of
`bin`)
=> update the link to download artifdactory OSS

ApplicationDeveloperGuide/UI/MicroUI/traces.rst
https://docs.microej.com/en/feature-m0127cc-686_improve_mui_traces_doc
=> Improve mui debug traces chapter

ApplicationDeveloperGuide/index.rst, ApplicationDeveloperGuide/nlsExternalLoader.rst
https://docs.microej.com/en/feature-m0078ddg-344_nls-external-loader/ApplicationDeveloperGuide/nlsExternalLoader.html#nls-external-loader
=> M0078DDG-344 Document NLS External Loader

overview/repository.rst
also update central repository to get the same structure
This MR is required before the Central Repository v3 is published.
=> document developer repository

ApplicationDeveloperGuide/heapUsageMonitoring.rst
While there, remove MicroEJ in names.
=> Mention that automatic heap monitoring is only available on device

ApplicationDeveloperGuide/moduleNatures.rst
- I kept the alphabetical order for the Module Natures
- I did not factorized the properties with the Standalone Application nature since it would make it less readable IMO
=> M0078DDG-467 Add Kernel in Module Natures page

PlatformDeveloperGuide/platformCreation.rst
See also: https://gitlab.cross/M0090_IDE/M0090_Easyant/-/merge_requests/443
=> fix options "No BSP connection, executable file built using MicroEJ SDK"

PlatformDeveloperGuide/appendix/toolchain.rst
=> M0081MEJA-1679 document ARM Cortex-M compatible versions

PlatformDeveloperGuide/platformCreation.rst
Doc preview: https://docs.microej.com/en/feature-m0137w-660_platform-publication/
=> M0137W-660 Add section for Platform Publication

ApplicationDeveloperGuide/linker.rst, PlatformDeveloperGuide/coreEngine.rst, PlatformDeveloperGuide/sp.rst
And fix wrong folder path in the SP documentation.
https://docs.microej.com/en/feature-timeslice/PlatformDeveloperGuide/coreEngine.html#scheduling
=> Document round-robin time slice configuration

SDKUserGuide/systemRequirements.rst
=> clearly indicate the status of macOS Intel & M1 chips

_themes/microej/layout.html, _themes/microej/static/css/microej.css
https://youtrack.cross/issue/M0078DDG-478
=> M0078DDG-478 Remove "Features" link in header menu

ApplicationDeveloperGuide/moduleNatures.rst, SDKUserGuide/mmm.rst
Document how to override organisation/name/revision of a module. It also adds the property of the debug mode.
=> M0090IDE-3762 Document how to override orgnisation/name/revision of a module

PlatformDeveloperGuide/appendix/toolchain.rst
- Add a section to document the group option with GNU LD.
=> Add GNU LD specific options

PlatformDeveloperGuide/platformCreation.rst
- Add a few sentences to explain how to find an Architecture dependency.
=> Detail how to select the Architecture dependency

PlatformDeveloperGuide/platformOverview.rst, PlatformDeveloperGuide/platformQualification.rst, Tutorials/tutorialUnderstandMicroEJFirmwareBuild.rst
- Remove "MicroEJ" when possible
- Rewording of some sentences
- Typos
=> M0078DDG-502 Update Tutorial Understand How To build a Firmware

ApplicationDeveloperGuide/platformSelection.rst, PlatformDeveloperGuide/platformCreation.rst, PlatformDeveloperGuide/platformMigration.rst
Preview: https://docs.microej.com/en/feature-m0078ddg-509_platform-selection-min-sdk/
=> M0078DDG-509 Add a note on minimum SDK version to use zip Platforms

ApplicationDeveloperGuide/moduleNatures.rst
https://docs.microej.com/en/feature-m0090ide-4129_add_property_to_skip_null_analysis_checker/ApplicationDeveloperGuide/moduleNatures.html#artifact-checker
=> add skip.nullanalysis.checker property

SDKUserGuide/installSDKDistributionLatest.rst, SDKUserGuide/installSDKDistributionOther.rst, SDKUserGuide/installSDKDistributionPortable.rst, SDKUserGuide/sdkChangeLog.rst, SDKUserGuide/systemRequirements.rst
https://docs.microej.com/en/feature-m0090ide-4006_distri_23.02/
=> add SDK Distri 23.02

SDK6UserGuide/howtos/gradleSkipTask.rst, SDK6UserGuide/howtos/index.rst
https://docs.microej.com/en/feature-microej-sdk-6-skip-task/SDK6UserGuide/howtos/gradleSkipTask.html
=> document how to skip a Gradle task

SDK6UserGuide/createProject.rst, SDK6UserGuide/install.rst, SDK6UserGuide/migrateMMMProject.rst
https://docs.microej.com/en/feature-microej-sdk-6-use-gradle-8.x/
=> Update SDK 6 to version 0.5.0 and set the Gradle compatible version to 8.0.2 and higher

ApplicationDeveloperGuide/applicationOptions.rst
https://docs.microej.com/en/feature-microej-sdk-6-application-properties-files/ApplicationDeveloperGuide/applicationOptions.html#defining-an-option-with-sdk-6
=> document how to define Application options with multiple VEE Ports

VEEPortingGuide/architectureChangelog.rst
https://docs.microej.com/en/feature-architecture_7.20.1/VEEPortingGuide/architectureChangelog.html
=> Add changelog for Architecture 7.20.1

SDKUserGuide/troubleshooting.rst
Add quarantine message when installing the SDK on macOS Aarch64.
=> M0078DDG-535 Add quarantine message when installing the SDK on macOS Aarch64

VEEPortingGuide/systemView.rst
See https://docs.microej.com/en/feature-review_systemview/VEEPortingGuide/systemView.html
=> Review systemview documentation wording.

SDK6UserGuide/testProject.rst
https://docs.microej.com/en/feature-sdk6-testsuite/
=> M0090IDE-4172 Document the new test capabilities of the SDK 6

Tutorials/tutorialCreateFirmwareFromScratch.rst
- Fix numbered list
- Fix reference to a properties file
- Fix link to commit
=> Minor fixes in tutorial "Create a MicroEJ Firmware From Scratch":

ApplicationDeveloperGuide/classpath.rst, VEEPortingGuide/architectureChangelog.rst
=> added resource alignment constraint specicication and changelog

VEEPortingGuide/architectureChangelog.rst
also document related Object size computation fix on Sim
=> document Module.getAllocatedMemory

SDK6UserGuide/buildExecutable.rst, SDK6UserGuide/buildProject.rst, SDK6UserGuide/createProject.rst, SDK6UserGuide/howtos/gradleSkipTask.rst, SDK6UserGuide/howtos/gradleSystemProperty.rst, SDK6UserGuide/publishProject.rst, SDK6UserGuide/runOnSimulator.rst, SDK6UserGuide/testProject.rst
https://docs.microej.com/en/feature-microej-sdk-6-wrapper/
=> document the Gradle Wrapper

.readthedocs.yml
This reverts commit 43f632200fbd5beba7273b4c56eef9adb6995a30.
=> Revert "Disable linkcheck"

SDKUserGuide/licenses.rst
New tested solution for USB redirection over network
=> Add https://www.virtualhere.com/

SDKUserGuide/systemRequirements.rst, SDKUserGuide/troubleshooting.rst
Add SDK Distribution max version for JavaSoft (Oracle) registry keys option<
=> Add SDK Distribution max version for JavaSoft (Oracle) registry keys option

SDK6UserGuide/moduleNatures.rst, SDK6UserGuide/selectVeePort.rst
https://docs.microej.com/en/feature-microej-sdk-6_merge_veeport_properties/
=> merge veePortFiles and veePortDirs properties

SDK6UserGuide/appendix/virtualDevice.rst, SDK6UserGuide/buildVirtualDevice.rst
https://docs.microej.com/en/feature-microej-application/SDK6UserGuide/buildVirtualDevice.html#add-an-application-in-a-virtual-device
=> Add section to add Applications in a VD

SDK6UserGuide/selectKernel.rst
https://docs.microej.com/en/feature-microej-sdk-6-remove-microejkernel-conf/SDK6UserGuide/selectKernel.html
=> remove the microejKernel configuration

SDK6UserGuide/selectVeePort.rst
https://docs.microej.com/en/feature-select-vee-port/SDK6UserGuide/selectVeePort.html
=> Add more context in the VEE Port selection page

SDK6UserGuide/createProject.rst, SDK6UserGuide/migrateMMMProject.rst, SDK6UserGuide/sdk6ChangeLog.rst
https://docs.microej.com/en/feature-microej-sdk-6_0.10.0/
=> Release SDK 6 0.10.0

SDK6UserGuide/graphApplicationModule.dot, SDK6UserGuide/moduleNatures.rst
Added the runOnDevice task and fixed the properties in the moduleNatures page  : https://docs.microej.com/en/feature-microej-sdk-6-update_modulenatures_page/SDK6UserGuide/moduleNatures.html
=> update the moduleNatures page

KernelDeveloperGuide/kernelCreation.rst, VEEPortingGuide/architectureChangelog.rst, VEEPortingGuide/multiSandbox.rst
See:
- https://docs.microej.com/en/feature-m0081meja-2241_ramcontrol/VEEPortingGuide/architectureChangelog.html#mm-dd
- https://docs.microej.com/en/feature-m0081meja-2241_ramcontrol/VEEPortingGuide/multiSandbox.html#ram-control
- https://docs.microej.com/en/feature-m0081meja-2241_ramcontrol/KernelDeveloperGuide/kernelCreation.html#configure-a-vee-port
=> ﻿Add RAM Control documentation.

SDK6UserGuide/createProject.rst, SDK6UserGuide/howtos/buildExecutableWithMultipleVeePorts.rst, SDK6UserGuide/migrateMMMProject.rst, SDK6UserGuide/sdk6ChangeLog.rst
https://docs.microej.com/en/feature-microej-sdk-6-0.12.0/
=> Release 0.12.0

SDK6UserGuide/buildFeature.rst, SDK6UserGuide/graphApplicationModule.dot, SDK6UserGuide/moduleNatures.rst, SDK6UserGuide/runOnSimulator.rst, SDK6UserGuide/sdk6MigrationNotes.rst, SDK6UserGuide/selectKernel.rst, SDK6UserGuide/selectVeePort.rst
https://docs.microej.com/en/feature-microej-sdk-6-microejkernel-configuration/
=> document the microejKernel configuration

SDK6UserGuide/createProject.rst, SDK6UserGuide/howtos/buildExecutableWithMultipleVeePorts.rst, SDK6UserGuide/migrateMMMProject.rst, SDK6UserGuide/sdk6ChangeLog.rst
https://docs.microej.com/en/feature-microej-sdk-6-0.12.1/
=> Release 0.12.1

SDK6UserGuide/moduleNatures.rst
https://docs.microej.com/en/feature-microej-sdk-6-tasks-inputs-outputs/SDK6UserGuide/moduleNatures.html
=> Document the tasks' inputs and outputs

VEEPortingGuide/frontpanel.rst, VEEPortingGuide/uiSimulation.rst
fix comments to be compatible with https://gitlab.cross/M0092_MicroEJ-Architecture-UI/M0092_UI-FrontPanel-Plugin/-/merge_requests/17
=> clarify the front panel project dependencies

glossary.rst
@jerome-leroux I'm not sure about the "managed-C" and "asm" terms usage
=> update glossary with C/Managed C languages

SDKUserGuide/installSDKDistributionOther.rst, SDKUserGuide/installSDKDistributionPortable.rst
- https://microej-docs--780.com.readthedocs.build/en/780/SDKUserGuide/installSDKDistributionOther.html
- https://microej-docs--780.com.readthedocs.build/en/780/SDKUserGuide/installSDKDistributionPortable.html
=> Remove free access on SDK 5 portable archives

ApplicationDeveloperGuide/index.rst, ApplicationDeveloperGuide/javaTime.rst, ApplicationDeveloperGuide/libraries.rst
preview: https://docs.microej.com/en/feature-java-time/ (links to not yet published resources may break the doc build)
Will merge when library is published on central repo
=> Add page for java time + write introduction

SDK6UserGuide/codeCoverageAnalyzer.rst, SDK6UserGuide/runOnSimulator.rst, SDK6UserGuide/tools.rst
=> Feature/m0090 ide 4446 Add code coverage analyzer and how to enable code coverage cc generation

SDK6UserGuide/createProject.rst, SDK6UserGuide/howtos/buildExecutableWithMultipleVeePorts.rst, SDK6UserGuide/migrateMMMProject.rst, SDK6UserGuide/moduleNatures.rst, SDK6UserGuide/publishProject.rst, SDK6UserGuide/sdk6ChangeLog.rst
https://docs.microej.com/en/feature-microej-sdk-6_0.13.0/
=> Release 0.13.0

SDK6UserGuide/publishProject.rst
https://docs.microej.com/en/feature-microej-sdk-6-publish-executable/SDK6UserGuide/publishProject.html
=> document optional publication of an Executable and a Feature

ApplicationDeveloperGuide/runtime.rst, KernelDeveloperGuide/kf.rst, VEEPortingGuide/sp.rst
- moved to repository.microej.com
- PDFs revision update with new copyright notice
=> update ESR specifications links

SDK6UserGuide/howtos/resolveInIDE.rst, SDK6UserGuide/install.rst, SDK6UserGuide/tools.rst
https://docs.microej.com/en/feature-sdk6_clarify_composite_build/SDK6UserGuide/howtos/resolveInIDE.html
=> clarify documentation about Composite builds

SDK6UserGuide/licenses.rst
https://docs.microej.com/en/feature-fix_sdk6_license_page/SDK6UserGuide/licenses.html#evaluation-licenses
=> fix SDK 6 license page

VEEPortingGuide/architecture.rst, VEEPortingGuide/architectureReleaseNotes.rst
See https://docs.microej.com/en/feature-arch_release_notes/VEEPortingGuide/architectureReleaseNotes.html
=> Add Architecture Release Notes

VEEPortingGuide/architectureChangelog.rst
See https://docs.microej.com/en/feature-m0081meja-2445_changelog_7.16.x/VEEPortingGuide/architectureChangelog.html#id28
=> M0081MEJA-2445 Add the changelog of the Architectures 7.16.x

SDK6UserGuide/troubleshooting.rst
https://microej-docs--831.com.readthedocs.build/en/831/SDK6UserGuide/troubleshooting.html#unresolved-dependency
=> M0090IDE-4515 Add troubleshooting section on dependencies fetch and SSL certificate issue

SDK6UserGuide/appendix/dependenciesConfigurations.rst, SDK6UserGuide/appendix/graphConfigurations.dot, SDK6UserGuide/appendix/index.rst, SDK6UserGuide/publishProject.rst
https://docs.microej.com/en/feature-microej-sdk-6-develop/
=> Document Dependency management and produceExecutableDuringBuild()/produceFeatureDuringBuild() methods

SDK6UserGuide/limitations.rst, SDK6UserGuide/selectKernel.rst, SDK6UserGuide/selectVeePort.rst
https://docs.microej.com/en/feature-sdk6_remove_dropins_support/
=> remove support of dropIns folder for MicroEJ VEE selection

SDK6UserGuide/addDependency.rst, SDK6UserGuide/appendix/dependenciesConfigurations.rst, SDK6UserGuide/appendix/graphConfigurations.dot, SDK6UserGuide/graphAddonLibraryModule.dot, SDK6UserGuide/graphApplicationModule.dot, SDK6UserGuide/howtos/gradleSystemProperty.rst, SDK6UserGuide/migrateMMMProject.rst, SDK6UserGuide/moduleNatures.rst, SDK6UserGuide/sdk6MigrationNotes.rst, SDK6UserGuide/selectKernel.rst, SDK6UserGuide/selectVeePort.rst, SDK6UserGuide/troubleshooting.rst
https://docs.microej.com/en/feature-sdk6_microejvee/
=> Unify VEE dependency declaration

SDK6UserGuide/appendix/graphConfigurations.dot, SDK6UserGuide/buildExecutable.rst, SDK6UserGuide/buildFeature.rst, SDK6UserGuide/buildVirtualDevice.rst, SDK6UserGuide/createProject.rst, SDK6UserGuide/graphApplicationModule.dot, SDK6UserGuide/howtos/buildExecutableWithMultipleVeePorts.rst, SDK6UserGuide/howtos/index.rst, SDK6UserGuide/howtos/useFeatureEntryPointClass.rst, SDK6UserGuide/migrateMMMProject.rst, SDK6UserGuide/moduleNatures.rst, SDK6UserGuide/publishProject.rst, SDK6UserGuide/runOnDevice.rst, SDK6UserGuide/runOnSimulator.rst, SDK6UserGuide/sdk6MigrationNotes.rst
https://docs.microej.com/en/feature-sdk6_unify_application_entrypoint/
=> unify application entrypoint

SDK6UserGuide/buildVirtualDevice.rst, SDK6UserGuide/publishProject.rst
https://docs.microej.com/en/feature-sdk6_buildvirtualdevice_with_kernel/
=> allow to build a Virtual Device with a Kernel

SDK6UserGuide/addDependency.rst, SDK6UserGuide/migrateMMMProject.rst, SDK6UserGuide/resources/microej.init.gradle.kts, conf.py
This should help on the migration to SDK 6 (mix SDK 5 / SDK 6 environment).
=> Resolve local MMM modules from SDK 6

SDK6UserGuide/appendix/graphConfigurations.dot, SDK6UserGuide/graphApplicationModule.dot, SDK6UserGuide/moduleNatures.rst, SDK6UserGuide/testProject.rst
https://docs.microej.com/en/feature-sdk6_remove_wrapapplication_task/
=> remove the wrapApplication task

Tutorials/tutorialSoftwareRobot.rst
`robot` is not declared so the code snippet of EventRecorder was not working.
=> Remove robot. from EventRecorder

SDK6UserGuide/graphApplicationModule.dot, SDK6UserGuide/graphMockModule.dot, SDK6UserGuide/moduleNatures.rst
https://docs.microej.com/en/feature-sdk6_mock_plugin_and_exectool_task/SDK6UserGuide/moduleNatures.html
=> document Mock plugin and execTool task in moduleNatures page

SDK6UserGuide/howtos/gradleMultiRepositories.rst, SDK6UserGuide/howtos/index.rst, SDK6UserGuide/install.rst, Tutorials/tutorialCreateFirmwareFromScratch.rst
https://docs.microej.com/en/feature-configure_gradle_repo/SDK6UserGuide/install.html
=> Explain how to use properties to configure Gradle repository.

ApplicationDeveloperGuide/runtime.rst, VEEPortingGuide/architectureChangelog.rst, VEEPortingGuide/platformCreation.rst
they are available as constants
Also inline the typical code for printing formatted charcteristics on standard output. This is the code embedded in the default pre-built app.
=> document architecture characteristics

SDK6UserGuide/buildExecutable.rst, SDK6UserGuide/buildFeature.rst, SDK6UserGuide/buildVirtualDevice.rst, SDK6UserGuide/publishProject.rst
https://docs.microej.com/en/feature-sdk6_document_producevirtualdeviceduringbuild/SDK6UserGuide/publishProject.html
=> document how to skip the publication of a Virtual Device

SDK6UserGuide/addDependency.rst, SDK6UserGuide/appendix/graphConfigurations.dot, SDK6UserGuide/buildExecutable.rst, SDK6UserGuide/buildFeature.rst, SDK6UserGuide/buildVirtualDevice.rst, SDK6UserGuide/createProject.rst, SDK6UserGuide/graphApplicationModule.dot, SDK6UserGuide/howtos/buildExecutableWithMultipleVeePorts.rst, SDK6UserGuide/howtos/index.rst, SDK6UserGuide/howtos/useFeatureEntryPointClass.rst, SDK6UserGuide/migrateMMMProject.rst, SDK6UserGuide/moduleNatures.rst, SDK6UserGuide/runOnDevice.rst, SDK6UserGuide/runOnSimulator.rst, SDK6UserGuide/sdk6ChangeLog.rst, SDK6UserGuide/sdk6MigrationNotes.rst, SDK6UserGuide/testProject.rst, SDK6UserGuide/troubleshooting.rst, VEEWearUserGuide/android/projectSetup.rst
https://docs.microej.com/en/feature-sdk6_develop/
=> SDK 6 Release 0.16.0

Tutorials/tutorialCreateFirmwareFromScratch.rst
https://youtrack.cross/issue/M0078DDG-560/Update-architecture-used-in-Create-a-MicroEJ-Firmware-From-Scratch-Tutorial
=> M0078DDG-560 Update architecture used in Create a MicroEJ Firmware From Scratch Tutorial

SDK6UserGuide/graphAddonLibraryModule.dot, SDK6UserGuide/graphApplicationModule.dot, SDK6UserGuide/moduleNatures.rst
https://docs.microej.com/en/feature-sdk6_remove_loadconfiguration_tasks/SDK6UserGuide/moduleNatures.html
=> remove loadConfiguration tasks

SDK6UserGuide/howtos/useFeatureEntryPointClass.rst
https://docs.microej.com/en/feature-sdk6_add_kf_dependency_in_usefeatureentrypointclass_howto/SDK6UserGuide/howtos/useFeatureEntryPointClass.html
=> Document KF dependency in the FeatureEntryPoint HowTo guide

SDK6UserGuide/appendix/applicationWrapper.rst, SDK6UserGuide/appendix/index.rst, SDK6UserGuide/graphApplicationModule.dot, SDK6UserGuide/moduleNatures.rst
https://docs.microej.com/en/feature-sdk6_document_generateapplicationwrapper_task/SDK6UserGuide/moduleNatures.html
=> document generateApplicationWrapper task

SDK6UserGuide/appendix/applicationWrapper.rst
https://docs.microej.com/en/feature-sdk6_fix_wrapper_class_main_method/SDK6UserGuide/appendix/applicationWrapper.html
=> fix wrapper class main method

KernelDeveloperGuide/runtimeEnvironment.rst, SDK6UserGuide/appendix/dependenciesConfigurations.rst, SDK6UserGuide/appendix/graphConfigurations.dot, SDK6UserGuide/buildVirtualDevice.rst, SDK6UserGuide/graphApplicationModule.dot, SDK6UserGuide/moduleNatures.rst
https://docs.microej.com/en/feature-sdk6_document_runtime_api_configuration/
=> Document Runtime API configuration

SDK6UserGuide/howtos/disableIvyDescriptorPublication.rst, SDK6UserGuide/howtos/index.rst, SDK6UserGuide/howtos/installSnapshotPlugins.rst, SDK6UserGuide/publishProject.rst
https://docs.microej.com/en/feature-sdk6_disable_ivy_publication/
=> Add an how-to section to disable Ivy descriptor publication with SDK 6.

SDK6UserGuide/heapAnalyzer.rst
https://microej-docs--935.com.readthedocs.build/en/935/SDK6UserGuide/heapAnalyzer.html#retrieve-the-hex-file-from-the-device
=> Explicit steps to use dumps generated by 'VEE memory dump macro script'

SDK6UserGuide/limitations.rst, SDK6UserGuide/serialToSocketTransmitter.rst, SDK6UserGuide/testProject.rst, SDK6UserGuide/tools.rst
Update SDK 6 scope page and Add Serial to Socket Transmitter in SDK 6 documentation
=> Update SDK 6 scope page and Add Serial to Socket Transmitter in SDK 6 documentation

KernelDeveloperGuide/kf.rst
when an app is paused in a monitor
=> add  to CPU control specification the behaviour

SDK6UserGuide/appendix/dependenciesConfigurations.rst, SDK6UserGuide/appendix/graphConfigurations.dot, SDK6UserGuide/buildExecutable.rst, SDK6UserGuide/buildFeature.rst, SDK6UserGuide/graphAddonLibraryModule.dot, SDK6UserGuide/migrateMMMProject.rst, SDK6UserGuide/moduleNatures.rst
https://docs.microej.com/en/feature-sdk6_fixes/
=> Update tasks documentation and dependencies configurations

SDK6UserGuide/buildVirtualDevice.rst, SDK6UserGuide/runOnSimulator.rst, SDK6UserGuide/selectKernel.rst
https://docs.microej.com/en/feature-document_microejapplication/
=> document how to execute dependent applications on simulator

ApplicationDeveloperGuide/characterEncoding.rst, VEEPortingGuide/sni.rst
https://microej-docs--1055.com.readthedocs.build/en/1055/VEEPortingGuide/sni.html#strings
=> Add example for SNI String conversions

KernelDeveloperGuide/applicationLink.rst, KernelDeveloperGuide/kernelCreation.rst, KernelDeveloperGuide/runtimeEnvironment.rst
https://docs.microej.com/en/feature-sdk6_update_kernel_creation_page/KernelDeveloperGuide/kernelCreation.html
=> update kernel creation page with SDK 6

SDK6UserGuide/install.rst
https://microej-docs--1068.com.readthedocs.build/en/1068/
=> Reload Java project in VS Code after the extension update only if a project is opened

SDK6UserGuide/howtos/createCustomExecToolTask.rst, SDK6UserGuide/howtos/index.rst, SDK6UserGuide/localDeployTool.rst
https://docs.microej.com/en/feature-sdk6_create_custom_exectool_tasks/SDK6UserGuide/howtos/createCustomExecToolTask.html
=> document how to create custom ExecTool tasks

SDK6UserGuide/troubleshooting.rst
https://docs.microej.com/en/feature-sdk6_testsuite_dependencies/SDK6UserGuide/troubleshooting.html#resolution-conflict-with-testsuite-dependencies
=> add troubleshooting for resolution conflict with testsuite dependencies

SDK6UserGuide/manageVersion.rst, conf.py
=> M0078DDG-555 Stop side nav bar from scrolling with the rest of the page

.readthedocs.yml, ApplicationDeveloperGuide/managedc/getting_started.rst, SDK6UserGuide/licenses.rst, SDKUserGuide/licenses.rst
This branch adds instructions that demonstrate how to run the Managed Getting started with SDK6
=> Add SDK 6 instructions

SDK6UserGuide/howtos/createCustomConfigurationInIDE.rst
https://docs.microej.com/en/feature-sdk6_quotes_in_vs_code/SDK6UserGuide/howtos/createCustomConfigurationInIDE.html
=> add warning about task options with quotes in VS Code

VEEPortingGuide/appendix/cmodules.rst, VEEPortingGuide/appendix/index.rst
Add a section to describe how to manually install a C module.
=> Create the C modules section

ApplicationDeveloperGuide/managedc/troubleshooting.rst
=> document out of bounds typical exceptions

SDK6UserGuide/sdk6MigrationNotes.rst
https://docs.microej.com/en/feature-migration-sdk6-troubleshooting/SDK6UserGuide/sdk6MigrationNotes.html
=> Add troubleshooting section when executing a testsuite after an SDK 6 upgrade

ApplicationDeveloperGuide/sectionArchitectureOptions.rst, VEEPortingGuide/mock.rst
https://docs.microej.com/en/feature-hil_frame_size/VEEPortingGuide/mock.html#mocks-design-support
=> Add Note to explain how to increase HIL maximum frame size

ApplicationDeveloperGuide/limitations.rst, VEEPortingGuide/architectureChangelog.rst
required for FSO compatibility
=> fix limitation to 127 threads for Architecture 8.4.0

ApplicationDeveloperGuide/runtime.rst, SDK6UserGuide/appendix/index.rst, SDK6UserGuide/appendix/javaLambdas.rst
https://docs.microej.com/en/feature-sdk6_lambdas/
=> document how to enable lambdas

VEEPortingGuide/mock.rst
https://docs.microej.com/en/feature-javafx_with_sdk6/VEEPortingGuide/mock.html#javafx
=> clarify how to declare JavaFX dependency in SDK 6

KernelDeveloperGuide/runtimeEnvironment.rst
=> Remove warning on compatibility issue between Runtime Environment

VEEPortingGuide/architectureChangelog.rst
=> fix missing libraries

support.rst
- highlight and update versions
- add SDK 6
=> update support page

SDK6UserGuide/createProject.rst
https://docs.microej.com/en/feature-gradle-9/SDK6UserGuide/createProject.html
=> Update Gradle version compatibility to exclude Gradle 9
